### PR TITLE
TASK: Use jquery.focuspoint for the landing page image

### PR DESCRIPTION
**Pull request by dfeyer**
This change use the jquery.focuspoint to make sure the landing page image
is correctly cropped in different resolution.

### CODE REVIEW

**Comment by dfeyer** [comment]
Before

before

After

after

**Comment by dfeyer** [comment]
It solve also other case, like huge width small height ratio, and others

**Comment by kdambekalns** [comment]
This looks like a great change… but since the image changed, the focus point data needs to be adjusted. :)

**Comment by jonnitto** [comment]
Closing this, as we going to refactor this page anyway. Thank you Dominique for all your work!

**Pull request closed without merging**
