### PR TITLE
TASK: Replace Neos.Ui.NodeInfo.inBackend in favour of Neos.Node.inBackend

### PR DESCRIPTION
**Pull request by dlubitz**

### CODE REVIEW

**Comment by mhsdesign** [comment]
nice lets wait for https://github.com/neos/Neos.Demo/pull/142 as we would need to redo it after the refactor (and could forget it ^^)

**Comment by ahaeslich** [comment]
I would rather merge this first as there we will probably need to check more things.

**Comment by mhsdesign** [comment]
i see we have https://github.com/neos/Neos.Demo/issues/156 already for this ^^

**Comment by ahaeslich** [comment]
> i see we have https://github.com/neos/Neos.Demo/issues/156 already for this ^^

😉

**Pull request merged**
