### PR TITLE
!!! TASK: Update Neos.Demo after the adjusting Neos.NodeTypes

### PR DESCRIPTION
**Pull request by mficzel**
- Update Sites.xml after node migration 20190304111200
- Remove dependency to Neos.NodeTypes
- Add dependency to Neos.Nodetypes.BaseMixins
- Add dependency to Neos.NodeTypes.Assetlist,
- Add dependency to Neos.NodeTypes.ContentReferences
- Add dependency to Neos.NodeTypes.Form
- Add dependency to Neos.NodeTypes.Html
- Add dependency to Neos.NodeTypes.Navigation
- Avoid usage of Neos.Nodetypes Nodes via constraint instead of overriding NodeTypes with `abstract=true`
- Raise version constraint for neos to ^5.0 || dev-master
- Remove dependency to Neos.Seo as this is already required by the base distribution and is not needed by Neos.Demo itself

### CODE REVIEW

**Comment by kdambekalns** [comment]
Last commit inspired by https://github.com/neos/neos-development-collection/pull/2683

**Comment by Sebobo** [comment]
Shouldn't the current Neos.Seo be used instead of removing it?

**Comment by mficzel** [comment]
@sebobo Neos.Seo is required by the base distribution already so it is and will stay part of a default Neos installation.

A site package as Neos.Demo should only have a depency to Neos.Seo if it extends or overrides parts of it. Since this is not the case Neos.Seo is not a dependency of Neos.Demo.

**Comment by Sebobo** [comment]
K. Just wondered as it was unrelated to the topic of the PR.

**Pull request merged**
